---
# ansible-playbook file.yml

- name: run tasks on all hosts
  hosts: "*"
  tasks:
          - debug: var=ansible_host

          - name: copy file to remote hosts
            copy:
                    src: test_file
                    dest: $HOME/testfile
