---
# ansible-playbook yum.yml

- name: run tasks on all hosts
  hosts: centos
  #  become: true
  #  become_user: root
  tasks:
          #    - name: install epel repo
          #      yum:
          #        name: epel-release
          #        state: present
          #        update_cache: true
          #      become: true
          #    - name: Let's copy our proxy script to remote hosts
          #      copy: src=/etc/ansible/scripts/centos81test4Proxy.sh dest=/$HOME mode=0777
          #
          #    - name: Execute the Proxy script
          #      command: sh /$HOME/centos81test4Proxy.sh
          #
          #    - name: install kernel packages
          #      yum:
          #        name: 
          #         - kernel-devel
          #         - kernel-headers
          #         - kernel
          #         - gcc
          #         - gcc-c++
          #         - make  
          #        state: present
          #        update_cache: true
          #      become: true
          #    - name: install requirements for Driver update
          #      yum:
          #        name: 
          ##        - elfutils-libelf-devel
          #         - libtool
          #         - automake
          #         - autoconf
          #         - cmake
          #         - libnl3-devel
          #         - libudev-devel
          #         - pkgconfig
          #         - valgrind-devel
          #         - pciutils
          #         - lshw
          #        state: present
          #        update_cache: true
          #      become: true
          #
          #    - name: Reboot the server and wait for it to come back up.
          #      reboot:
          #        connect_timeout: 5
          #        msg: "Reboot initiated by Ansible"
          #        reboot_timeout: 600
          #        pre_reboot_delay: 0
          #        post_reboot_delay: 30
          #        search_paths: ["/sbin","/usr/sbin","usr/local/sbin"] 
          #        test_command: "whoami"
          #      become: true
          #
          #    - name: install htop
          #      yum:
          #        name:
          #         - htop
          #        state: present
          #        update_cache: true
          #      become: true

    - name: Let's copy our Pensando script to remote hosts
      copy: src=/etc/ansible/scripts/centos81PensandoInstall_script2.sh dest=/$HOME mode=0777
      become: true

    - name: Execute the Pensando script
      command: sh /$HOME/centos81PensandoInstall_script2.sh
      become: true

